#!/bin/sh

# build without debug printing

gcc -Wall -Wextra -D release socd.c -o socd -Ofast -march=native -g -flto -ffast-math -funroll-loops -fgcse -fomit-frame-pointer -fdata-sections -ffunction-sections -fstrict-aliasing
